version: "3.8"

services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_EXPOSED_PORT}:80
    volumes:
      - ./databases/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  postgres:
    image: postgres:12.7
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    volumes:
      - ./databases/postgresql/${POSTGRES_DATABASE_NAME}:/var/lib/postgresql/data
    restart: unless-stopped
  flyway:
    image: flyway/flyway:7.9
    container_name: flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE_NAME}
      - FLYWAY_SCHEMAS=${MIGRATION_SCHEMA}
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql/
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_SQL_MIGRATION_PREFIX=V
      - FLYWAY_SQL_MIGRATION_SEPARATOR=__
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: migrate
    volumes:
      - ${MIGRATION_SRC}:/flyway/sql
    depends_on:
      - postgres